#!/usr/bin/env bash

set -e

sub_name=$1

if [ -z "$1" ]; then
	echo "Please provide a name for the new sub !"
	exit 1
fi

# Clone the base repo
echo "Cloning basecamp/sub..."
git clone git@github.com:basecamp/sub.git $sub_name 2>/dev/null

# Go into the newly clone repo
pushd $sub_name 1>/dev/null

# Prepare the new sub
echo "Preparing the new sub..."
./prepare.sh $sub_name 1>/dev/null

# Clean up .git folder
echo "cleaning up..."
rm -Rf .git
rm -Rf share

# Finished, exit repo
popd 1>/dev/null
