#!/usr/bin/env bash

set -e

sub_name="$1"

if [[ -z "$sub_name" ]]; then
	echo "New sub name not specified."
fi

# Clone basecamp/sub
git clone https://github.com/basecamp/sub.git "$sub_name" 2>/dev/null

pushd "$sub_name" 1>/dev/null

# Prepare sub and clean up
./prepare.sh "$sub_name" 1>/dev/null
rm -Rf .git
rm -Rf share
popd 1>/dev/null

echo "New sub $sub_name initialized."
